spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springboot01?serverTimezone=UTC&useSSL=false
    username: root
    password: a123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
      max-active: 100
server:
  port: 8080
